# Generated by Django 4.2.2 on 2023-08-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_address_options_alter_bannerimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(help_text='لطفاً تصویری با ابعاد 1921 در 966  پیکسل وارد کنید', upload_to='image/banner', verbose_name='تصویر بنر'),
        ),
    ]
