# Generated by Django 4.2.2 on 2023-08-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_bannerimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس\u200c'},
        ),
        migrations.AlterModelOptions(
            name='bannerimage',
            options={'verbose_name': 'تصویر بنر', 'verbose_name_plural': 'تصویر بنر'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'ایمیل', 'verbose_name_plural': 'ایمیل ها\u200c'},
        ),
        migrations.AlterModelOptions(
            name='numberlist',
            options={'verbose_name': 'لیست شماره\u200cها', 'verbose_name_plural': 'لیست شماره\u200c'},
        ),
    ]
