# Generated by Django 4.2.2 on 2023-10-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourmission',
            name='icon',
            field=models.FileField(blank=True, help_text='فایل آیکون مرتبط با مأموریت خود را انتخاب کنید.', null=True, upload_to='icon', verbose_name='ایکون(اختیاری)'),
        ),
    ]
