# Generated by Django 4.2.2 on 2023-08-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='bannerimage',
            options={'verbose_name': 'تصویر بنر', 'verbose_name_plural': 'تصاویر بنر'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'اطلاعات تماس', 'verbose_name_plural': 'اطلاعات تماس'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'ایمیل', 'verbose_name_plural': 'ایمیل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='number',
            options={'verbose_name': 'شماره تماس', 'verbose_name_plural': 'شماره\u200cهای تماس'},
        ),
        migrations.AlterModelOptions(
            name='numberlist',
            options={'verbose_name': 'لیست شماره\u200cها', 'verbose_name_plural': 'لیست شماره\u200cها'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=200, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(upload_to='image/banner', verbose_name='تصویر بنر'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(help_text='مثال: example@example.com', max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='email',
            name='text',
            field=models.CharField(blank=True, help_text='توضیحاتی درباره ایمیل', max_length=200, null=True, verbose_name='متن(اختیاری)'),
        ),
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.CharField(help_text='مثال: 09121234567', max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='number',
            name='text',
            field=models.CharField(blank=True, help_text='توضیحاتی درباره این شماره تماس.', max_length=200, null=True, verbose_name='متن(اختیاری)'),
        ),
        migrations.AlterField(
            model_name='numberlist',
            name='number',
            field=models.CharField(help_text='مثال: 09121234567', max_length=20, verbose_name='شماره'),
        ),
    ]
