# Generated by Django 4.2.2 on 2023-08-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_address_options_alter_bannerimage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumberList',
        ),
        migrations.RemoveField(
            model_name='email',
            name='text',
        ),
        migrations.RemoveField(
            model_name='number',
            name='text',
        ),
    ]
