# Generated by Django 4.2.2 on 2023-08-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_delete_numberlist_remove_email_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='link',
            field=models.CharField(blank=True, max_length=9999, null=True, verbose_name='لینک(اختیاری)'),
        ),
    ]
