# Generated by Django 4.2.2 on 2023-08-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutus_mission_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباره ما'},
        ),
        migrations.AlterModelOptions(
            name='bannerimageabout',
            options={'verbose_name': 'تصویر بنر درباره ما', 'verbose_name_plural': 'تصاویر بنر درباره ما'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'ماموریت', 'verbose_name_plural': 'ماموریت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'تیم', 'verbose_name_plural': 'تیم'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='image/about', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='team',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='image/team', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='team',
            name='job',
            field=models.CharField(max_length=100, verbose_name='سمت'),
        ),
    ]
