# Generated by Django 4.2.2 on 2023-10-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_team_instagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='instagram',
        ),
    ]
