# Generated by Django 4.2.2 on 2023-08-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_aboutus_image_alter_bannerimageabout_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerimageabout',
            options={'verbose_name': 'تصویر بنر درباره ما', 'verbose_name_plural': 'تصویر بنر درباره ما'},
        ),
    ]
