# Generated by Django 4.2.2 on 2023-10-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_remove_team_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک پیج اینستاگرام(اختیاری)'),
        ),
    ]
