# Generated by Django 4.2.2 on 2023-10-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='public',
            field=models.DateField(auto_now_add=True, verbose_name='تاربخ'),
        ),
    ]
